version: '2'
services:

    nginx:
        image: umputun/nginx-le:latest
        container_name: nginx-bot
        hostname: nginx-bot
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - ./etc/ssl:/etc/nginx/ssl
            - ./etc/nginx.conf:/etc/nginx/service.conf

        ports:
            - "80:80"
            - "443:443"

        environment:
           - TZ=America/Chicago
           - LETSENCRYPT=true
           - LE_EMAIL=umputun@gmail.com
           - LE_FQDN=bot.radio-t.com

        depends_on:
            - hello
            - memberberries
            - wiki-bot
            - search-bot
            - noter-bot
            - repl-bot

    hello:
        build: hello
        container_name: hello-bot
        hostname: hello-bot
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

    memberberries:
        build: memberberries
        container_name: memberberries-bot
        hostname: memberberries-bot
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

    wiki-bot:
        build: wiki-bot
        container_name: wiki-bot
        hostname: wiki-bot
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

    search-bot:
        build: search-bot
        container_name: search-bot
        hostname: search-bot
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

    noter-bot:
        build: noter-bot
        container_name: noter-bot
        hostname: noter-bot
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

    repl-bot:
        build: rt-repl-bot
        container_name: repl-bot
        hostname: repl-bot
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

    stat-bot:
        build: stat-bot
        container_name: stat-bot
        hostname: stat-bot
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

    gif-bot:
        build: gif-bot
        container_name: gif-bot
        hostname: gif-bot
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

    bots:
        build: bots
        container_name: bots-bot
        hostname: bots-bot
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"
